from pathlib import Path

ROOT = Path('.')

def replace_exact(path, old, new, count=1):
    p = ROOT / path
    text = p.read_text()
    actual = text.count(old)
    if actual != count:
        raise SystemExit(f'{path}: expected {count} matches, found {actual}')
    p.write_text(text.replace(old, new, count))

replace_exact(
    'app/build.gradle.kts',
    '        versionCode = 75\n        versionName = "0.74.0-robust-latency-learning"',
    '        versionCode = 76\n        versionName = "0.75.0-latency-regime-detection"')

replace_exact(
    'app/src/main/java/com/livecopilot/micprobe/RealtimeRoutingPolicy.java',
    '    static final long MAX_ROUTE_LATENCY_DROP_STEP_MS = 4_000L;\n',
    '    static final long MAX_ROUTE_LATENCY_DROP_STEP_MS = 4_000L;\n'
    '    static final int ROUTE_LATENCY_REGIME_CONFIRM_STREAK = 2;\n')

replace_exact(
    'app/src/main/java/com/livecopilot/micprobe/RealtimeRoutingPolicy.java',
    '''    static boolean isRouteLatencyOutlier(long currentEstimateMs, int currentSamples,\n                                         long sampleMs) {\n        return sampleMs >= 0L\n                && boundedRouteLatencySample(currentEstimateMs, currentSamples, sampleMs) != sampleMs;\n    }\n\n    static long nextRouteLatencyEstimate(long currentEstimateMs, int currentSamples,\n                                         long sampleMs) {\n        if (sampleMs < 0L) return currentEstimateMs;\n        long boundedSampleMs = boundedRouteLatencySample(\n                currentEstimateMs, currentSamples, sampleMs);\n        if (currentEstimateMs < 0L || currentSamples <= 0) return boundedSampleMs;\n        long safeEstimate = Math.max(0L, Math.min(MAX_ROUTE_LATENCY_SAMPLE_MS, currentEstimateMs));\n        return Math.max(0L, (safeEstimate * 3L + boundedSampleMs + 2L) / 4L);\n    }\n''',
    '''    static boolean isRouteLatencyOutlier(long currentEstimateMs, int currentSamples,\n                                         long sampleMs) {\n        return sampleMs >= 0L\n                && boundedRouteLatencySample(currentEstimateMs, currentSamples, sampleMs) != sampleMs;\n    }\n\n    static int routeLatencyOutlierDirection(long currentEstimateMs, int currentSamples,\n                                            long sampleMs) {\n        if (sampleMs < 0L || currentEstimateMs < 0L || currentSamples <= 0) return 0;\n        long boundedSampleMs = boundedRouteLatencySample(\n                currentEstimateMs, currentSamples, sampleMs);\n        if (sampleMs > boundedSampleMs) return 1;\n        if (sampleMs < boundedSampleMs) return -1;\n        return 0;\n    }\n\n    static int nextRouteLatencyOutlierStreak(int currentDirection, int currentStreak,\n                                             int nextDirection, boolean previousEvidenceFresh) {\n        if (nextDirection == 0) return 0;\n        if (!previousEvidenceFresh || nextDirection != currentDirection) return 1;\n        int safe = Math.max(0, Math.min(ROUTE_LATENCY_REGIME_CONFIRM_STREAK, currentStreak));\n        return Math.min(ROUTE_LATENCY_REGIME_CONFIRM_STREAK, safe + 1);\n    }\n\n    static boolean isRouteLatencyRegimeChange(int direction, int outlierStreak) {\n        return direction != 0 && outlierStreak >= ROUTE_LATENCY_REGIME_CONFIRM_STREAK;\n    }\n\n    static long regimeAwareRouteLatencySample(long currentEstimateMs, int currentSamples,\n                                              long sampleMs, int outlierDirection,\n                                              int outlierStreak) {\n        if (sampleMs < 0L) return sampleMs;\n        if (isRouteLatencyRegimeChange(outlierDirection, outlierStreak)) {\n            return Math.min(MAX_ROUTE_LATENCY_SAMPLE_MS, sampleMs);\n        }\n        return boundedRouteLatencySample(currentEstimateMs, currentSamples, sampleMs);\n    }\n\n    static long nextRouteLatencyEstimate(long currentEstimateMs, int currentSamples,\n                                         long sampleMs) {\n        return nextRouteLatencyEstimate(currentEstimateMs, currentSamples, sampleMs, 0, 0);\n    }\n\n    static long nextRouteLatencyEstimate(long currentEstimateMs, int currentSamples,\n                                         long sampleMs, int outlierDirection,\n                                         int outlierStreak) {\n        if (sampleMs < 0L) return currentEstimateMs;\n        long boundedSampleMs = regimeAwareRouteLatencySample(\n                currentEstimateMs, currentSamples, sampleMs, outlierDirection, outlierStreak);\n        if (currentEstimateMs < 0L || currentSamples <= 0) return boundedSampleMs;\n        long safeEstimate = Math.max(0L, Math.min(MAX_ROUTE_LATENCY_SAMPLE_MS, currentEstimateMs));\n        return Math.max(0L, (safeEstimate * 3L + boundedSampleMs + 2L) / 4L);\n    }\n''')

replace_exact(
    'app/src/main/java/com/livecopilot/micprobe/RealtimeRoutingPolicy.java',
    '''    static long nextRouteLatencyJitter(long currentJitterMs, long currentEstimateMs,\n                                       int currentSamples, long sampleMs) {\n        if (sampleMs < 0L) return currentJitterMs;\n        if (currentEstimateMs < 0L || currentSamples <= 0) return 0L;\n        long safeEstimate = Math.max(0L, Math.min(MAX_ROUTE_LATENCY_SAMPLE_MS, currentEstimateMs));\n        long boundedSampleMs = boundedRouteLatencySample(\n                safeEstimate, currentSamples, sampleMs);\n        long deviation = Math.abs(boundedSampleMs - safeEstimate);\n        if (currentSamples <= 1 || currentJitterMs < 0L) {\n            return Math.min(MAX_ROUTE_LATENCY_JITTER_MS, deviation);\n        }\n        long safeJitter = Math.max(0L, Math.min(MAX_ROUTE_LATENCY_JITTER_MS, currentJitterMs));\n        long next = (safeJitter * 3L + deviation + 2L) / 4L;\n        return Math.min(MAX_ROUTE_LATENCY_JITTER_MS, Math.max(0L, next));\n    }\n''',
    '''    static long nextRouteLatencyJitter(long currentJitterMs, long currentEstimateMs,\n                                       int currentSamples, long sampleMs) {\n        return nextRouteLatencyJitter(\n                currentJitterMs, currentEstimateMs, currentSamples, sampleMs, 0, 0);\n    }\n\n    static long nextRouteLatencyJitter(long currentJitterMs, long currentEstimateMs,\n                                       int currentSamples, long sampleMs,\n                                       int outlierDirection, int outlierStreak) {\n        if (sampleMs < 0L) return currentJitterMs;\n        if (currentEstimateMs < 0L || currentSamples <= 0) return 0L;\n        long safeEstimate = Math.max(0L, Math.min(MAX_ROUTE_LATENCY_SAMPLE_MS, currentEstimateMs));\n        long boundedSampleMs = regimeAwareRouteLatencySample(\n                safeEstimate, currentSamples, sampleMs, outlierDirection, outlierStreak);\n        long deviation = Math.abs(boundedSampleMs - safeEstimate);\n        if (currentSamples <= 1 || currentJitterMs < 0L) {\n            return Math.min(MAX_ROUTE_LATENCY_JITTER_MS, deviation);\n        }\n        long safeJitter = Math.max(0L, Math.min(MAX_ROUTE_LATENCY_JITTER_MS, currentJitterMs));\n        long next = (safeJitter * 3L + deviation + 2L) / 4L;\n        return Math.min(MAX_ROUTE_LATENCY_JITTER_MS, Math.max(0L, next));\n    }\n''')

replace_exact(
    'app/src/main/java/com/livecopilot/micprobe/RealtimeTranscriptionClient.java',
    '''    private long realtimeRouteLatencyEstimateMs = -1L;\n    private long realtimeRouteLatencyJitterMs = -1L;\n    private int realtimeRouteLatencySamples;\n    private long realtimeRouteLatencySampleAtMs;\n    private long fileRouteLatencyEstimateMs = -1L;\n    private long fileRouteLatencyJitterMs = -1L;\n    private int fileRouteLatencySamples;\n    private long fileRouteLatencySampleAtMs;\n''',
    '''    private long realtimeRouteLatencyEstimateMs = -1L;\n    private long realtimeRouteLatencyJitterMs = -1L;\n    private int realtimeRouteLatencySamples;\n    private long realtimeRouteLatencySampleAtMs;\n    private int realtimeRouteLatencyOutlierDirection;\n    private int realtimeRouteLatencyOutlierStreak;\n    private long fileRouteLatencyEstimateMs = -1L;\n    private long fileRouteLatencyJitterMs = -1L;\n    private int fileRouteLatencySamples;\n    private long fileRouteLatencySampleAtMs;\n    private int fileRouteLatencyOutlierDirection;\n    private int fileRouteLatencyOutlierStreak;\n''')

replace_exact(
    'app/src/main/java/com/livecopilot/micprobe/RealtimeTranscriptionClient.java',
    '''        realtimeRouteLatencyEstimateMs = -1L;\n        realtimeRouteLatencyJitterMs = -1L;\n        realtimeRouteLatencySamples = 0;\n        realtimeRouteLatencySampleAtMs = 0L;\n        fileRouteLatencyEstimateMs = -1L;\n        fileRouteLatencyJitterMs = -1L;\n        fileRouteLatencySamples = 0;\n        fileRouteLatencySampleAtMs = 0L;\n''',
    '''        realtimeRouteLatencyEstimateMs = -1L;\n        realtimeRouteLatencyJitterMs = -1L;\n        realtimeRouteLatencySamples = 0;\n        realtimeRouteLatencySampleAtMs = 0L;\n        realtimeRouteLatencyOutlierDirection = 0;\n        realtimeRouteLatencyOutlierStreak = 0;\n        fileRouteLatencyEstimateMs = -1L;\n        fileRouteLatencyJitterMs = -1L;\n        fileRouteLatencySamples = 0;\n        fileRouteLatencySampleAtMs = 0L;\n        fileRouteLatencyOutlierDirection = 0;\n        fileRouteLatencyOutlierStreak = 0;\n''')

replace_exact(
    'app/src/main/java/com/livecopilot/micprobe/RealtimeTranscriptionClient.java',
    '''        if (RealtimeRoutingPolicy.isRealtimePerformanceSampleEligible(\n                acceptedUseful, fileRecovery, latencyMs)) {\n            long previousEstimateMs = realtimeRouteLatencyEstimateMs;\n            int previousSamples = realtimeRouteLatencySamples;\n            realtimeRouteLatencyJitterMs = RealtimeRoutingPolicy.nextRouteLatencyJitter(\n                    realtimeRouteLatencyJitterMs, previousEstimateMs, previousSamples, latencyMs);\n            realtimeRouteLatencyEstimateMs = RealtimeRoutingPolicy.nextRouteLatencyEstimate(\n                    previousEstimateMs, previousSamples, latencyMs);\n            realtimeRouteLatencySamples = RealtimeRoutingPolicy.nextRouteLatencySampleCount(\n                    previousSamples, latencyMs);\n            realtimeRouteLatencySampleAtMs = now;\n        }\n''',
    '''        if (RealtimeRoutingPolicy.isRealtimePerformanceSampleEligible(\n                acceptedUseful, fileRecovery, latencyMs)) {\n            long previousEstimateMs = realtimeRouteLatencyEstimateMs;\n            int previousSamples = realtimeRouteLatencySamples;\n            long previousSampleAtMs = realtimeRouteLatencySampleAtMs;\n            boolean previousEvidenceFresh = previousSampleAtMs > 0L\n                    && now >= previousSampleAtMs\n                    && now - previousSampleAtMs <= RealtimeRoutingPolicy.ROUTE_LATENCY_SAMPLE_MAX_AGE_MS;\n            int nextDirection = RealtimeRoutingPolicy.routeLatencyOutlierDirection(\n                    previousEstimateMs, previousSamples, latencyMs);\n            int nextOutlierStreak = RealtimeRoutingPolicy.nextRouteLatencyOutlierStreak(\n                    realtimeRouteLatencyOutlierDirection, realtimeRouteLatencyOutlierStreak,\n                    nextDirection, previousEvidenceFresh);\n            realtimeRouteLatencyJitterMs = RealtimeRoutingPolicy.nextRouteLatencyJitter(\n                    realtimeRouteLatencyJitterMs, previousEstimateMs, previousSamples, latencyMs,\n                    nextDirection, nextOutlierStreak);\n            realtimeRouteLatencyEstimateMs = RealtimeRoutingPolicy.nextRouteLatencyEstimate(\n                    previousEstimateMs, previousSamples, latencyMs,\n                    nextDirection, nextOutlierStreak);\n            realtimeRouteLatencySamples = RealtimeRoutingPolicy.nextRouteLatencySampleCount(\n                    previousSamples, latencyMs);\n            realtimeRouteLatencySampleAtMs = now;\n            realtimeRouteLatencyOutlierDirection = nextDirection;\n            realtimeRouteLatencyOutlierStreak = nextOutlierStreak;\n        }\n''')

replace_exact(
    'app/src/main/java/com/livecopilot/micprobe/RealtimeTranscriptionClient.java',
    '''        if (performanceEligible && drainLatencyMs >= 0L) {\n            long previousEstimateMs = fileRouteLatencyEstimateMs;\n            int previousSamples = fileRouteLatencySamples;\n            fileRouteLatencyJitterMs = RealtimeRoutingPolicy.nextRouteLatencyJitter(\n                    fileRouteLatencyJitterMs, previousEstimateMs, previousSamples, drainLatencyMs);\n            fileRouteLatencyEstimateMs = RealtimeRoutingPolicy.nextRouteLatencyEstimate(\n                    previousEstimateMs, previousSamples, drainLatencyMs);\n            fileRouteLatencySamples = RealtimeRoutingPolicy.nextRouteLatencySampleCount(\n                    previousSamples, drainLatencyMs);\n            fileRouteLatencySampleAtMs = now;\n        } else if (!performanceEligible) {\n            // A degraded/cooldown file lane cannot keep winning on stale speed history,\n            // even if its transcript coverage was still usable enough for context.\n            fileRouteLatencyEstimateMs = -1L;\n            fileRouteLatencyJitterMs = -1L;\n            fileRouteLatencySamples = 0;\n            fileRouteLatencySampleAtMs = 0L;\n        }\n''',
    '''        if (performanceEligible && drainLatencyMs >= 0L) {\n            long previousEstimateMs = fileRouteLatencyEstimateMs;\n            int previousSamples = fileRouteLatencySamples;\n            long previousSampleAtMs = fileRouteLatencySampleAtMs;\n            boolean previousEvidenceFresh = previousSampleAtMs > 0L\n                    && now >= previousSampleAtMs\n                    && now - previousSampleAtMs <= RealtimeRoutingPolicy.ROUTE_LATENCY_SAMPLE_MAX_AGE_MS;\n            int nextDirection = RealtimeRoutingPolicy.routeLatencyOutlierDirection(\n                    previousEstimateMs, previousSamples, drainLatencyMs);\n            int nextOutlierStreak = RealtimeRoutingPolicy.nextRouteLatencyOutlierStreak(\n                    fileRouteLatencyOutlierDirection, fileRouteLatencyOutlierStreak,\n                    nextDirection, previousEvidenceFresh);\n            fileRouteLatencyJitterMs = RealtimeRoutingPolicy.nextRouteLatencyJitter(\n                    fileRouteLatencyJitterMs, previousEstimateMs, previousSamples, drainLatencyMs,\n                    nextDirection, nextOutlierStreak);\n            fileRouteLatencyEstimateMs = RealtimeRoutingPolicy.nextRouteLatencyEstimate(\n                    previousEstimateMs, previousSamples, drainLatencyMs,\n                    nextDirection, nextOutlierStreak);\n            fileRouteLatencySamples = RealtimeRoutingPolicy.nextRouteLatencySampleCount(\n                    previousSamples, drainLatencyMs);\n            fileRouteLatencySampleAtMs = now;\n            fileRouteLatencyOutlierDirection = nextDirection;\n            fileRouteLatencyOutlierStreak = nextOutlierStreak;\n        } else if (!performanceEligible) {\n            // A degraded/cooldown file lane cannot keep winning on stale speed history,\n            // even if its transcript coverage was still usable enough for context.\n            fileRouteLatencyEstimateMs = -1L;\n            fileRouteLatencyJitterMs = -1L;\n            fileRouteLatencySamples = 0;\n            fileRouteLatencySampleAtMs = 0L;\n            fileRouteLatencyOutlierDirection = 0;\n            fileRouteLatencyOutlierStreak = 0;\n        }\n''')

path = ROOT / 'app/src/test/java/com/livecopilot/micprobe/RealtimeRoutingPolicyTest.java'
text = path.read_text()
anchor = '''    @Test\n    public void riskAdjustedLatencyRejectsFastButSpikyFileLane() {\n'''
if text.count(anchor) != 1:
    raise SystemExit('test anchor mismatch')
insert = '''    @Test\n    public void repeatedSameDirectionOutliersConfirmRegimeChange() {\n        long estimate = 1_600L;\n        int samples = 3;\n\n        int firstDirection = RealtimeRoutingPolicy.routeLatencyOutlierDirection(\n                estimate, samples, 8_000L);\n        int firstStreak = RealtimeRoutingPolicy.nextRouteLatencyOutlierStreak(\n                0, 0, firstDirection, true);\n        long firstEstimate = RealtimeRoutingPolicy.nextRouteLatencyEstimate(\n                estimate, samples, 8_000L, firstDirection, firstStreak);\n        assertEquals(1, firstDirection);\n        assertEquals(1, firstStreak);\n        assertFalse(RealtimeRoutingPolicy.isRouteLatencyRegimeChange(\n                firstDirection, firstStreak));\n        assertEquals(2_350L, firstEstimate);\n\n        int secondDirection = RealtimeRoutingPolicy.routeLatencyOutlierDirection(\n                firstEstimate, samples + 1, 8_000L);\n        int secondStreak = RealtimeRoutingPolicy.nextRouteLatencyOutlierStreak(\n                firstDirection, firstStreak, secondDirection, true);\n        long regimeEstimate = RealtimeRoutingPolicy.nextRouteLatencyEstimate(\n                firstEstimate, samples + 1, 8_000L, secondDirection, secondStreak);\n        long ordinaryEstimate = RealtimeRoutingPolicy.nextRouteLatencyEstimate(\n                firstEstimate, samples + 1, 8_000L);\n\n        assertEquals(1, secondDirection);\n        assertEquals(2, secondStreak);\n        assertTrue(RealtimeRoutingPolicy.isRouteLatencyRegimeChange(\n                secondDirection, secondStreak));\n        assertEquals(3_763L, regimeEstimate);\n        assertEquals(3_100L, ordinaryEstimate);\n        assertTrue(regimeEstimate > ordinaryEstimate);\n    }\n\n    @Test\n    public void inlierOrDirectionFlipBreaksRegimeStreak() {\n        assertEquals(0, RealtimeRoutingPolicy.routeLatencyOutlierDirection(\n                2_000L, 4, 3_000L));\n        assertEquals(0, RealtimeRoutingPolicy.nextRouteLatencyOutlierStreak(\n                1, 2, 0, true));\n\n        int downDirection = RealtimeRoutingPolicy.routeLatencyOutlierDirection(\n                8_000L, 4, 1_000L);\n        assertEquals(-1, downDirection);\n        assertEquals(1, RealtimeRoutingPolicy.nextRouteLatencyOutlierStreak(\n                1, 2, downDirection, true));\n    }\n\n    @Test\n    public void staleEvidenceCannotConfirmRegimeChange() {\n        assertEquals(1, RealtimeRoutingPolicy.nextRouteLatencyOutlierStreak(\n                1, 1, 1, false));\n        assertFalse(RealtimeRoutingPolicy.isRouteLatencyRegimeChange(1, 1));\n    }\n\n    @Test\n    public void confirmedRegimeStillHonorsAbsoluteLatencyCap() {\n        assertEquals(12_000L, RealtimeRoutingPolicy.regimeAwareRouteLatencySample(\n                1_600L, 3, Long.MAX_VALUE, 1, 2));\n        assertEquals(0L, RealtimeRoutingPolicy.regimeAwareRouteLatencySample(\n                8_000L, 3, 0L, -1, 2));\n    }\n\n'''
path.write_text(text.replace(anchor, insert + anchor))
